# Default values for cli-persistent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environmentType: production

gitSha: ""

image: ""

persistentStorage:
  name: ""

imagePullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# This flag controls the injection of the pod securityContext values below.
# It is intended to assist with phased rollout of rootless workloads.
# It is set to true via the build-time environment variable:
# LAGOON_ROOTLESS_WORKLOAD=true
rootless: false
podSecurityContext:
  fsGroup: 10001
  runAsGroup: 0
  runAsUser: 10000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 10m
    memory: 10Mi

nodeSelector: {}

tolerations: []

affinity: {}

inPodCronjobs: ""

nativeinPodCronjobs: ""

configMapSha: ""
